"""
This type stub file was generated by pyright.
"""

from ._rbm import BernoulliRBM
from ._multilayer_perceptron import MLPClassifier, MLPRegressor

"""
The :mod:`sklearn.neural_network` module includes models based on neural
networks.
"""
