"""
This type stub file was generated by pyright.
"""

from ._classes import BaseDecisionTree, DecisionTreeClassifier, DecisionTreeRegressor, ExtraTreeClassifier, ExtraTreeRegressor
from ._export import export_graphviz, export_text, plot_tree

"""
The :mod:`sklearn.tree` module includes decision tree-based models for
classification and regression.
"""
