"""
This type stub file was generated by pyright.
"""

import pytest
from sklearn.datasets import fetch_20newsgroups, fetch_20newsgroups_vectorized, fetch_california_housing, fetch_covtype, fetch_kddcup99, fetch_olivetti_faces, fetch_rcv1

dataset_fetchers = { 'fetch_20newsgroups_fxt': fetch_20newsgroups,'fetch_20newsgroups_vectorized_fxt': fetch_20newsgroups_vectorized,'fetch_california_housing_fxt': fetch_california_housing,'fetch_covtype_fxt': fetch_covtype,'fetch_kddcup99_fxt': fetch_kddcup99,'fetch_olivetti_faces_fxt': fetch_olivetti_faces,'fetch_rcv1_fxt': fetch_rcv1 }
fetch_20newsgroups_fxt = _fetch_fixture(fetch_20newsgroups)
fetch_20newsgroups_vectorized_fxt = _fetch_fixture(fetch_20newsgroups_vectorized)
fetch_california_housing_fxt = _fetch_fixture(fetch_california_housing)
fetch_covtype_fxt = _fetch_fixture(fetch_covtype)
fetch_kddcup99_fxt = _fetch_fixture(fetch_kddcup99)
fetch_olivetti_faces_fxt = _fetch_fixture(fetch_olivetti_faces)
fetch_rcv1_fxt = _fetch_fixture(fetch_rcv1)
def pytest_collection_modifyitems(config, items):
    """Called after collect is completed.

    Parameters
    ----------
    config : pytest config
    items : list of collected items
    """
    ...

@pytest.fixture(scope='function')
def pyplot():
    """Setup and teardown fixture for matplotlib.

    This fixture checks if we can import matplotlib. If not, the tests will be
    skipped. Otherwise, we setup matplotlib backend and close the figures
    after running the functions.

    Returns
    -------
    pyplot : module
        The ``matplotlib.pyplot`` module.
    """
    ...

def pytest_runtest_setup(item):
    """Set the number of openmp threads based on the number of workers
    xdist is using to prevent oversubscription.

    Parameters
    ----------
    item : pytest item
        item to be processed
    """
    ...

