"""
This type stub file was generated by pyright.
"""

from ._univariate_selection import GenericUnivariateSelect, SelectFdr, SelectFpr, SelectFwe, SelectKBest, SelectPercentile, chi2, f_classif, f_oneway, f_regression
from ._variance_threshold import VarianceThreshold
from ._rfe import RFE, RFECV
from ._from_model import SelectFromModel
from ._sequential import SequentialFeatureSelector
from ._mutual_info import mutual_info_classif, mutual_info_regression
from ._base import SelectorMixin

"""
The :mod:`sklearn.feature_selection` module implements feature selection
algorithms. It currently includes univariate filter selection methods and the
recursive feature elimination algorithm.
"""
