"""
This type stub file was generated by pyright.
"""

def palplot(pal, size=...):
    """Plot the values in a color palette as a horizontal array.

    Parameters
    ----------
    pal : sequence of matplotlib colors
        colors, i.e. as returned by seaborn.color_palette()
    size :
        scaling factor for size of plot

    """
    ...

def dogplot(*_, **__):
    """Who's a good boy?"""
    ...

